### ISSUE TITLE
A command which lists the files in the current directory

### ISSUE THREAD

**Issue by steget** [PUGzera/DATX02-DIT561#50]
Usability tests have shown that users often want to see the current folders contents -- something similar to `ls` in a normal command line.

Suggested solution:
Add a command which makes use of [`getDirectoryContents`](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:getDirectoryContents) or [`listDirectory`](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:listDirectory) from System.Directory

**Comment by krangelov** [comment]
I also encountered that I needed this when I tested the tool. My proposal
instead is to implement the ":!" command from ghci. This will let the user
do whatever he/she needs. For instance:

:! ls

shows the current directory.
