### ISSUE TITLE
:load resets the GHC session's working directory

### ISSUE THREAD

**Issue by pvedin** [PUGzera/DATX02-DIT561#58]
Assume you have a folder `testfolder` containing a file `Person.hs`:
```
Daison> :cd testfolder
Working directory set to (...)/daison-frontend/testfolder
Daison> :open database.db
```
This creates a database inside `testfolder`.

However:
```
Daison> :cd testfolder
Working directory set to (...)/daison-frontend/testfolder
Daison> :load Person
Loaded (...)/daison-frontend/testfolder/Person
Daison> :open database.db
```

This creates a database inside `daison-frontend`, i.e. the initial working directory. However, the working directory is not completely reset:

```
Daison (database.db)> :l Person
module 'Person' is defined in multiple files: (...)/daison-frontend/testfolder/Person.hs
                                              (...)/daison-frontend/testfolder/Person.hs
```

Suggestions (preferably the first one):
- restore the GHC session's working directory after the user loads a file
- update `currentDirectory` in the `DaisonI` state after the user loads a file, and notify the user that the working directory has been changed.

**Comment by kaltenbrunner** [comment]
Fixed by 8866492df4da7e710b4233e174d3d5c7168d545d.
