### ISSUE TITLE
Certain commands do not work with :!

### ISSUE THREAD

**Issue by pvedin** [PUGzera/DATX02-DIT561#67]
These commands worked in an earlier version.
For example, if you have a file `Defs.hs`:
```
Daison> :! nano Defs.hs
Too many errors from stdin
readCreateProcess: nano DemoDefs.hs (exit 1): failed
```
My guess is that commands that expect user interaction currently do not work, as other commands such as `ls` still work.

**Comment by kaltenbrunner** [comment]
The problem with the code in the earlier version was that every command was run from the base directory. Thus,

```
:cd newdir
:! mkdir anotherdir
```

would create `../anotherdir/` instead of `anotherdir/`.
